### ISSUE TITLE
To string call before the serialization could take a chance to process an object for push & publish

### ISSUE THREAD

**Issue by acidumirae** [kestra-io/plugin-redis#21]
### Expected Behavior

JSON  serialization of the result set

{ "column1":"value1", "column2":"value2", ... }

https://tinypic.host/i/screenshot-2023-03-30-155129.INgFB

### Actual Behaviour

ToString() output:

{ column1=value1, column2=value2, ... }

https://tinypic.host/i/screenshot-2023-03-30-160849.INVw8

### Steps To Reproduce

1. Using io.kestra.plugin.redis.ListPush or io.kestra.plugin.redis.Publish send a complex result set to Redis
2. Inspect Redis for the pushed or published content

### Environment Information

- Kestra Version: 0.8.0-SNAPSHOT
- Plugin version: 0.8.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes): Windows 10 Pro 19045.2728 / Podman 4.4.1
- Java Version (If not docker):

**Comment by acidumirae** [comment]
There is a pull request that fixes that bug https://github.com/kestra-io/plugin-redis/pull/20

**Comment by anna-geller** [comment]
it seems that this PR fixed the issue https://github.com/kestra-io/plugin-redis/pull/25 

@loicmathieu please reopen if I'm mistaken
