### ISSUE TITLE
PUBLISH support

### ISSUE THREAD

**Issue by acidumirae** [kestra-io/plugin-redis#8]
### Feature description

Hello is there a reason why Redis plugin does not support PUBLISH?
A very important aspect of using Redis pub/sub is missing.
It could be essential in orchestration ETL pipelines, for example:

source => kestra => redis queue => existing consumer

It seems that the aim is to provide the end-to-end experience with symmetric input and output in case of SUBSCRIBE it could be a challenge for Kestra. Would you consider having PUBLISH only support?
It is very simple and straightforward, example:

https://github.com/kestra-io/plugin-redis/compare/master...acidumirae:plugin-redis:master

Thank you!

**Comment by tchiotludo** [comment]
I think it's done [here](https://kestra.io/plugins/plugin-redis/tasks/io.kestra.plugin.redis.publish), reopen if missing features
